spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/shixun?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.yznu.shixun.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
